### ISSUE TITLE
[META] Attention Stream v1.3 + Reconsent

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#131]
- [ ] EPIC: new metrics in Attention Stream v1.3
  - [x] [Talk to Laura at NYU](https://github.com/mozilla-rally/internal/issues/628) | [Notes document](https://docs.google.com/document/d/1HCEFqlUj5v_Avxb4HfrgHqoOwrCSk0K5As1a9qia_io/edit#heading=h.dhplh972ik3z)
  - [ ] [Define new metrics for Attention Stream v1.3 (September update)](https://github.com/mozilla-rally/rally/issues/147) and https://github.com/mozilla-rally/rally/issues/167
  - [ ] Build updates  
    - [x] #156
    - [x] #157
- [ ] EPIC: MVP Messaging / Notifications
  - [x] #159
- [ ] EPIC: MVP Consent / Reconsent
  - [ ] ~~#160~~  **replaced by:** 
    - [x] https://github.com/mozilla-rally/rally/issues/170
  - [ ] ~~#161~~  **replaced by:**
    - [ ] https://github.com/mozilla-rally/rally/issues/173 and
    - [ ] https://github.com/mozilla-rally/rally/issues/174
- [ ] EPIC: Partitioned Analysis Environment
  - [ ] #123
