### ISSUE TITLE
Cutover to React site

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#209]
- [x] #243 
- [x] https://github.com/mozilla-rally/rally/issues/224
- [x] Update DNS (https://mozilla-hub.atlassian.net/browse/DSRE-998)
- [x] [After DNS is updated, change email verification url to default in firebase](https://github.com/mozilla-rally/rally/issues/224#issuecomment-1241199999)
- [x] mozilla-rally/rally-web-platform#194 
- [x] mozilla-rally/rally-web-platform#177 
- [x] mozilla-rally/rally-web-platform#201 
- [x] mozilla-rally/rally-web-platform#207 
- [x] mozilla-rally/rally-web-platform#208 
- [x] mozilla-rally/rally-web-platform#234 
  - [x] stage
- [x] mozilla-rally/rally-web-platform#213
- [x] https://github.com/mozilla-rally/rally/issues/237
- [x] mozilla-rally/rally-web-platform#226 
- [x] #238

**Comment by jepstein** [comment]
cc @marniepw for visibility

**Comment by marniepw** [comment]
Updating staging today. 
If all looks good, we'll go live on Monday, Sept. 12, 2022, afternoon ET.
