### ISSUE TITLE
[META] Attention Stream - name change

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally#271]
We want to change the name of the Attention Stream extension to "Mozilla Rally".

Group 1:
- [x] Update the slug for the Core Add-on on AMO to be "rally-pilot-studies"
- [x] Update the name for the Core Add-on on AMO to be "Rally Pilot Studies"
- [x] [Update the Core Add-on link on the Marketing Site](https://github.com/mozilla-rally/site/pull/713)

Group 2:
- [x] [Update the `manifest.json` for the Attention Stream to use the new name](https://github.com/mozilla-rally/rally/pull/281) - _this has landed, but we are waiting on extension store reviews, and potentially waiting to get badged on AMO_
- [x] Update the name and slug on AMO to Mozilla Rally and "mozilla-rally"
- [x] Update the store URLs in Firebase
- [x] [Update the copy on the Members site - this needs more thought, are we at the stage of getting rid of the "studies" framework?](https://github.com/mozilla-rally/rally/issues/282)
- [ ] Update the marketing site copy and footers

The grouped items need to go live near simultaneously, and Group 1 should happen before Group 2.

**Comment by than-mozilla** [comment]
Core addon can be named `Rally Pilot Studies` for item 1.2 :)

**Comment by marniepw** [comment]
See also: https://github.com/mozilla-rally/internal/issues/629
