### ISSUE TITLE
[META] Onboarding Flow 2: Account Creation First

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#315]
This will serve as the meta ticket for Onboarding Flow 2 - Account Creation First. [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893). [Copy source](https://docs.google.com/document/d/1Qe378bDnNu0jj779SmxOnWYge8GbMlnB7tRSJIxHnkE/edit#).

- [x] [1a / 2a: Onboarding - Signup](https://github.com/mozilla-rally/rally/issues/316)
- [x] [1b: Onboarding - Sign up / Email, Password](https://github.com/mozilla-rally/rally/issues/317)
- [x] [1b1 / 2b1: Onboarding - Sign up / Email, Password: loading state](https://github.com/mozilla-rally/rally/issues/318)
- [x] https://github.com/mozilla-rally/rally/issues/335
- [x] https://github.com/mozilla-rally/rally/issues/320
- [x] https://github.com/mozilla-rally/rally/issues/321
