### ISSUE TITLE
1b / 2b: Onboarding - Sign up / Email, Password

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#317]
**As a user, I want to sign up for Rally using my email and password, so that I can participate in data sharing.**

**_The difference between 1b and 2b is the title of the screen and the instructional text_**
Screen 1b / 2b: Onboarding - Sign up / Email, Password.  [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893). [Copy doc](https://docs.google.com/document/d/1Qe378bDnNu0jj779SmxOnWYge8GbMlnB7tRSJIxHnkE/edit#).

- [ ] Onclick Mozilla Rally logo, return user to https://rally.mozilla.org/
- [ ] Headers
  - [ ] 1b Header: "Now let's create your account" Highlight on _your account_  
  - [ ] 2b Header: "Let's Rally. Create your account" Highlight on _your account_  
- [ ] Instructional text - see [doc](https://docs.google.com/document/d/1Qe378bDnNu0jj779SmxOnWYge8GbMlnB7tRSJIxHnkE/edit#) file for variations in 1b and 2b text
- [ ] Email field. _I imagine we do some kind of error checking / messaging?*_
- [ ] Password field. Obscure chars as users types. _I imagine we do some kind of error checking for something in this field?*_ 
- [ ] Optional email checkbox. On select, capture user's email and pass to...somewhere safe
- [ ] "Create account" button. Onclick*, flip "Create account" button to the state seen in [screen 1b1 / 2b1](https://github.com/mozilla-rally/rally/issues/318).

*I'm not writing out specs about checking for existing accounts, matching emails/passwords, emails, etc. I assume that functionality all exists. Happy path only, above.
