### ISSUE TITLE
1b1 / 2b1: Onboarding - Sign up / Email, Password: loading state

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#318]
**As a user, I want to know that my account creation is in progress, so that I can participate in data sharing.**

**_The difference between 1b1 and 2b1 is the title of the screen and the [instructional text](https://docs.google.com/document/d/1Qe378bDnNu0jj779SmxOnWYge8GbMlnB7tRSJIxHnkE/edit#)_**
- Screen 1b1: Onboarding - Sign up / Email, Password.  [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893)
- Screen 2b1: Onboarding - Sign up / Email, Password.  [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893)

This screen is the same as [1b](https://github.com/mozilla-rally/rally/issues/317), with the exception of the two fields and the loading state of the "Create account" button:
- [ ] The email and password fields should flip to a grey/inactive state. The user should not be able to edit these fields while the page is in this state.
- [ ] When the "Create account" button is in the creation state, the button should turn green (#54ffbd) and the text should change to "Creating account...": https://github.com/mozilla-rally/rally/issues/279
- [ ] When account creation is complete, take user to [screen 1c / 2c](https://github.com/mozilla-rally/rally/issues/319).

**Comment by jepstein** [comment]
Green for the button is `54ffbd`
