### ISSUE TITLE
1c / 2c: Onboarding - Privacy notice

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#319]
**As a user, I want to understand Rally's privacy policies, so that I can decide whether to participate in data sharing.**

Screen 1c / 2c: Onboarding - Privacy notice. [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893)
After an account is successfully created in [screen 1b1 / 2b1](https://github.com/mozilla-rally/rally/issues/318): 
- [x] https://github.com/mozilla-rally/rally/issues/275
- [x] Pop the privacy modal ([Source doc](https://docs.google.com/document/d/14Kh47_vWP3VVZOyfbCUKikzashUwFyiLGYMQWb6sGBc/edit#))
- [x] User must scroll to the bottom of the privacy notice before the "Agree" button is in the active state. (_Is this true?_)
- [x] Onpress "Agree" button, capture date/time of acceptance (same functionality as currently exists), and
- [x] #366
