### ISSUE TITLE
2d: Onboarding - Get the Extension

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#335]
**As a user, I've created my Rally account and now want to install the extension so that I may begin contributing data.**

Screen 2d: Onboarding - Get the Extension. [Figma source](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893)

- [x] Header: "Lastly, add the extension" Highlight on _extension_
- [x] Big ole bunch of instructional text: refer to the [copy doc](https://docs.google.com/document/d/1uekFPIAhxtifGzFpuMBRZxKq1BTUJXRW4hD-ge8joLE/edit) file for latest
- [x] Onclick "Add the extension": browser detect, taking the user to the correct extension store
- [x] Onclick "Skip for now": take the user to https://rally.mozilla.org/
- [x] Right 1/3 of page is grey with imagery, see [figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4372%3A92893) for the latest

**Comment by marniepw** [comment]
[Copy document](https://docs.google.com/document/d/1uekFPIAhxtifGzFpuMBRZxKq1BTUJXRW4hD-ge8joLE/edit)
