### ISSUE TITLE
Compensation vs. Donation Ads for Princeton

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#337]
- [x] Mock-ups @compzilla 
- [x] Graphic Copy @compzilla
- [x] Creatives (Threespot)
- [ ] Princeton requirements for branding/language
- [ ] UX Edit @tangcasey
- [ ] Revisions @tangcasey (not sure what Threespot uses - hoping figma - Casey, will you need access to their Figma?)
- [ ] Sized for all channels @tangcasey
- [x] Ad Copy for FB @compzilla
- [x] Graphics for FB @KennedyM-zillian
- [x] Ad Copy for GDN @compzilla 
- [x] Graphics for GDN  (Threespot)
- [ ] Ad copy for Pinterest @compzilla 
- [ ] Graphics for Pinterest (Threespot)
- [ ] Ad copy for Twitter @compzilla 
- [ ] Graphics for Twitter (Threespot)
- [ ] Ad copy for Reddit
- [ ] Graphics for Reddit
- [ ] CTAs @compzilla
- [x] Legal Approval @than-mozilla
- [x] Targeting @compzilla and @than-mozilla (we need to discuss strategy)
- 19+
- Both genders
- English-speaking
- Desktop
- Browser - should we JUST target Chrome (can do this on some channels not on others)
- U.S. - are we trying to fill in demographics of non-coastal states?
- Behaviors
- Target words
- Target brands
- [ ] UTM FB @compzilla
- [ ] UTM GDN  @compzilla 
- [ ] UTM Pinterest @compzilla
- [ ] UTM Twitter
- [ ] UTM Reddit
- [ ] Budget @KimBMozilla
- [ ] Flight Scheduled @compzilla
- [ ] Operational upload (Threespot)
- [ ] Launched @compzilla

**Comment by compzilla** [comment]
Ahhhhh, I think i understand the [META] nesting now, @marniepw 🥇

**Comment by compzilla** [comment]
Here are the Princeton Mock-Ups. They've been posted in the Princeton slack channel as well as the Rally team slack channel. @KennedyM-zillian will manage haranguing the Princeton team to select, make suggestions, and give feedback.
https://docs.google.com/document/d/13gYtwuORnByY8yaCmtI66J0uhtRg0I1S9YAUdPq8gf0/edit#heading=h.pwexo1uw8jom

**Comment by compzilla** [comment]
Ted and I discussed targeting, and we will not be targeting behaviors/keywords/brand affinities or anything along those lines.

**Comment by compzilla** [comment]
Because of IRB requirements, both ads will be directed to the PAID Princeton landing page.

**Comment by compzilla** [comment]
@marniepw, if I @ mention ppl in the main issue (as above), are those ppl notified? If not, how do I assign a task to more than one person. Currently, I am unable to do that.

**Comment by compzilla** [comment]
Princeton's Survey is still not live, and we cannot start ads until it is live.
