### ISSUE TITLE
Compensation vs. Donation Ads for Stanford

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#338]
- [x] Mock-ups @compzilla 
- [x] Graphic Copy @compzilla
- [ ] UX Edit @tangcasey 
- [ ] Revisions @tangcasey (not sure what Threespot uses - hoping figma - Casey, will you need access to their Figma?)
- [x] Creatives (Threespot)
- [ ] Sized for all channels @tangcasey 
- [ ] Ad Copy @compzilla 
- [ ] CTA @compzilla 
- [ ] Legal Approval @than-mozilla 
- [ ] Targeting @compzilla and @than-mozilla (we need to discuss strategy)
- 19+
- Both genders
- English-speaking
- Laptop
- Browser - should we JUST target Chrome (can do this on some channels not on others)
- U.S. - are we trying to fill in demographics of non-coastal states?
- Behaviors
- Target words
- Target brands
- [ ] UTM @compzilla 
- [ ] Budget @KimBMozilla 
- [ ] Flight Scheduled @compzilla
- [ ] Operational upload (Threespot)
- [ ] Launched @compzilla
