### ISSUE TITLE
[META] Epic 4: Test User Compensation as a Value Proposition

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#344]
This will serve as the meta ticket for **Epic 4: Test User Compensation as a Value Proposition**

- [ ] https://github.com/mozilla-rally/rally/issues/337
- [ ] https://github.com/mozilla-rally/rally/issues/338
- [ ] https://github.com/mozilla-rally/rally/issues/339
- [ ] https://github.com/mozilla-rally/rally/issues/340
- [ ] https://github.com/mozilla-rally/rally/issues/343

**Comment by marniepw** [comment]
ThreeSpot ad images: https://www.figma.com/file/6tDjc91ogJRBTbNNq7C3i4/Join-Rally-Ad-Campaign?node-id=0%3A1

**Comment by marniepw** [comment]
Princeton copy/design spreadsheet: https://docs.google.com/spreadsheets/d/1GODt2j4jJAT_rEQNNMUgBhVbXwwbr9lCNNTncliN-P8/edit#gid=0

**Comment by marniepw** [comment]
Multiple attempts to contact Princeton; they're hiding from Kennedy.
