### ISSUE TITLE
Tell users that Rally is only available for users in the US at the start of the account creation

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally#359]
## Story

Tell users that Rally is only available for users in the US at the start of the account creation process & multiple times. 

## Tasks

- [ ] Figure out several moments along the user flow where we can communicate this
- [ ] Along with telling people this, include a link to the Newsletter where they can sign up to learn when we expand beyond US
- [ ] Consider creating a dropdown or text field where people can tell us where they live so we can act with more data when we expand beyond US
- [ ] If any study extension can be installed anywhere in the world, make sure the message we show (like the one below) includes a way for people to sign up for Rally and/or be notified via newsletter when we expand. (meaning: in addition to the ability to remove the extension which is the current behavior).

## User feedback

![Screen Shot 2022-04-29 at 1 47 06 PM](https://user-images.githubusercontent.com/1598889/166058328-cc200e0c-92fa-4e46-8716-5e06b10ab4aa.png)
