### ISSUE TITLE
[META] Platform Product Page

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#442]
As a Rally user, I want to see the user impacts of my data contribution, so that I can feel the benefits of participating.

[Figma with wireframes](https://www.figma.com/file/OVlnSF6b56ZDeHvhkkLWP4/Discovery-Page-Sketches----Fall-2022?node-id=0%3A1)

**DECISION**: Visualization: Number of trackers collected; this could continue to grow; we can update the stats as needed. Also shows a sense of community through ongoing collective action. Could break down by type/brand/platform of tracker.
Visualization will take up the bulk of the entire top “card” area.

**Schedule**
- [x] Monday, November 7: What data are available? Casey, Bruce, Ashwin
- [x] Tuesday, November 8: How do we display that data? Casey
- [x] Tuesday, November 8: Reconvene and make decision on data display. Casey, Bruce, Ashwin
- [x] Tuesday, November 8: Decide on content associated with data display. Three graphics to start, copy still needed, legends on images, including <alt text>.
- [x] Thursday, November 10: Layout of the page defined
- [x] Monday, Nov 14, implementation begins
- [x] #474
- [ ] Final copy edits: @KimBMozilla 
- [x] No “current projects” section for the shortened timeframe
- [ ] Demographics, toasts, contribution status (attention stream, need to live in a different view than previously)

https://github.com/mozilla-rally/rally/issues/453

**Comment by jepstein** [comment]
Next step is a meeting to decide on initial iteration of the product page among the following options --

- Highlight wins/accomplishments/past studies
- Highlight the community you’d be joining
- Giveback for unlocking final step in onboarding
- Sharing studies, results, my impact
   - What types of things do people want to share?
- Stanford’s tidbits; need to be repackaged (currently slanted towards data folks). 
- Highlight real folks on site: what impact have we had on specific people’s lives

**Comment by marniepw** [comment]
11/2 discussion: [recording link](https://mozilla.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=73bc96b9-ef80-41b5-95d2-af410115754e)
- Constraints: think about what data we have available for the first version of this page: content box where some kind of aggregate lives. 
  - Data type requirements: 
    - Legal requirement: Has to be in the privacy policy. 
    - Product requirement: Has to be somewhere the user can find it and review it. [Ted’s reply from signal](https://mozilla.slack.com/archives/C025YNEDGCB/p1667407706086469?thread_ts=1667407607.719579&cid=C025YNEDGCB)
- What’s most important to the user?
  - Value
    - Insights: 
      - Aggregate level: Going with this currently (Nov 2, 2022). Possible options:
      - # Rally users across U.S. states: community building
      - Impact links
      - Insight
      - Community (X users have contributed Y rows of data, or found N pixels)
      - Number of lawsuits
    - Research participants group level 
    - Individual level
      - A lot of data to choose from but do not know what is most valuable for end user
        - Need UR
    - Empowerment through action
      - Contribute data

**Comment by marniepw** [comment]
11/3 discussion: recording link

**Comment by marniepw** [comment]
Closing in favor of the newly created https://github.com/mozilla-rally/rally/issues/495
