### ISSUE TITLE
Hey Jane Pocket Ads (META)

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/rally#524]
- [x] mozilla-rally/rally#547
- [x] mozilla-rally/rally#548
- [x] mozilla-rally/rally#549
- [x] mozilla-rally/rally#550
- [x] mozilla-rally/rally#551
- [x] mozilla-rally/rally#552
- [x] mozilla-rally/rally#553
- [x] #459
- [x] #458
- [x] mozilla-rally/rally#554
- [x] mozilla-rally/rally#555
- [x] mozilla-rally/rally#556
- [x] #462
- [x] mozilla-rally/rally#558
- [x] #467
- [x] mozilla-rally/site#767
- [x] mozilla-rally/rally#560
- [x] mozilla-rally/rally#559
- [x] #461
- [x] #463
- [x] #464
- [x] #465
- [x] #466
- [x] #460

**Comment by compzilla** [comment]
Graphic ideas here: https://www.canva.com/design/DAFSimnJ2Ms/IGDLUpn_THLWQQkdmWwxdw/edit?utm_content=DAFSimnJ2Ms&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by compzilla** [comment]
Kennedy reviewed the graphics yesterday. Kim and Sydette reviewed them today. I'll make a few revisions and drop them in the Firefox New Tab Creative Assets Template here:  https://docs.google.com/spreadsheets/d/1jjlf0hezu5bhTm24GzCXWLWbK25Ogzoq6wUaQysyuJU/edit#gid=0

**Comment by compzilla** [comment]
![1](https://user-images.githubusercontent.com/111546319/205375644-f2bb9f11-448d-4d64-896c-654b6628ce00.jpg)

**Comment by compzilla** [comment]
![2](https://user-images.githubusercontent.com/111546319/205375707-0a3312b0-18e8-490d-b28d-fe2c7a5b9347.jpg)

**Comment by compzilla** [comment]
![3](https://user-images.githubusercontent.com/111546319/205375744-f84bb0ff-0fe3-4709-9fea-150942a01cae.jpg)

**Comment by compzilla** [comment]
UTM code: https://rally.mozilla.org/rally-for-womens-health/?utm_medium=cpc&utm_source=pocket&utm_campaign=womens-health-data

**Comment by compzilla** [comment]
Landing page copy: https://docs.google.com/document/d/1tMR-GlBn6atCyewATtIJKXbWpwV9_lWt8ahdXYY5Q-4/edit#

**Comment by compzilla** [comment]
Ad copy Headline and Excerpt Variants: https://docs.google.com/spreadsheets/d/1jjlf0hezu5bhTm24GzCXWLWbK25Ogzoq6wUaQysyuJU/edit#gid=0

**Comment by compzilla** [comment]
Page layout:

- Heroine image
- Our TLDR synthesis of the two stories copy
- CTA Join button
- HIPAA story
- Another CTA button
- Hey Jane Story
- One last CTA button (If they've read this far and don't join, they will at least be very well educated about the issue.)

**Comment by compzilla** [comment]
Landing page slug: 
https://rally.mozilla.org/rally-for-womens-health

**Comment by jepstein** [comment]
Preview at https://creative-sawine-573168.netlify.app/rally-for-womens-health/

**Comment by jepstein** [comment]
over here @marniepw

**Comment by marniepw** [comment]
Done and closing. Ads launched Dec 14/15 and results are coming in.
